<!-- nav.inc -->
<nav>
    <div class="navdiv">
        <!-- Nav & Header rearranged & header used as the main content title under teacher consult -->
        <img src="images/logo.png" alt="Logo" class="logo">
        <select name="navigation" id="navigation" onchange="dropdownDirect()">
            <option value="" selected disabled hidden>Select an option...</option>
            <option value="home">Home</option>
            <option value="pets">Pets</option>
            <option value="add">Add more</option>
            <option value="gallery">Gallery</option>
        </select> <input class="seperation right" type="text" placeholder="Search">
        <span class="material-symbols-outlined topmargin10 white marginleft">
            search
        </span>
    </div>
</nav>